[workspace]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["conda-forge"]
name = "profile-page"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
format = "npm install prettier && npx prettier --write index.html photography.html styles/main.css"

[dependencies]
python = ">=3.9"
pyyaml = "*"
jinja2 = "*"
omegaconf = "*"
nodejs = "*"
pillow = "*"
